FROM debian:bookworm

RUN apt update
RUN apt install gnupg2 -y

RUN echo "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu focal main" | tee /etc/apt/sources.list.d/linuxuprising-java.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 73C3DB2A
RUN apt update

RUN apt install binutils binutils-common binutils-x86-64-linux-gnu ca-certificates fonts-urw-base35 gsfonts-x11 java-common libbinutils \ 
 libbrotli1 libc-l10n libctf-nobfd0 libctf0 libfontenc1 libfreetype6 libgprofng0 libjansson4 libpng16-16 libpsl5 locales openssl \
 publicsuffix wget x11-common xfonts-encodings xfonts-utils libc-bin libc6 -y

RUN echo oracle-java17-installer shared/accepted-oracle-license-v1-3 select true | /usr/bin/debconf-set-selections
RUN apt install oracle-java17-installer -y
ENV JAVA_HOME="/usr/lib/jvm/java-17-oracle"

RUN apt install tomcat10 -y
ENV CATALINA_HOME="/usr/share/tomcat10"
ENV CATALINA_BASE="/var/lib/tomcat10"
ENV WEBAPPS_BASE="$CATALINA_BASE/webapps"
ENV PATH $CATALINA_HOME/bin:$PATH

###################################################################
# COPY lib/libtcnative-2.so /usr/lib
###################################################################

RUN mkdir /home/tomcat-native/
WORKDIR /home/tomcat-native/

RUN apt install libapr1-dev libssl-dev -y
RUN apt install gcc make -y

RUN wget https://dlcdn.apache.org/tomcat/tomcat-connectors/native/2.0.4/source/tomcat-native-2.0.4-src.tar.gz
RUN tar xzvf tomcat-native-2.0.4-src.tar.gz
WORKDIR tomcat-native-2.0.4-src/native
RUN ./configure --with-apr=/usr/bin --with-ssl=/usr && make
RUN cp .libs/libtcnative-2.so.0.0.4 /usr/lib/libtcnative-2.so
WORKDIR /home
RUN rm /home/tomcat-native -fr

COPY target/springbootangular.war $WEBAPPS_BASE

RUN apt install unzip -y

WORKDIR $WEBAPPS_BASE
RUN unzip springbootangular.war -d springbootangular
RUN rm springbootangular.war

ENV JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=prod"

RUN echo "<meta http-equiv='refresh' content='0;url=/springbootangular'/>" > /var/lib/tomcat10/webapps/ROOT/index.html

WORKDIR $WEBAPPS_BASE

EXPOSE 8080

CMD ["catalina.sh", "run"]